Feature/add zustand
Leeyaoi/InnoViber-frontend pull request #20
Opened 2024-07-02 15:08 UTC by Leeyaoi

2024-07-03 12:54 UTC, pavelGagarin0870 approved these changes

2024-07-04 08:26 UTC, Finka95 requested changes

2024-07-04 08:26 UTC, v12code commented on src/shared/states/ChatStates.ts
Move this file into src/state/chatSlise.tsx file

2024-07-04 08:26 UTC, v12code commented on src/shared/states/ChatStates.ts
> +        const res = await axios.get("https://localhost:7060/api/Chat");
what is localhost:7060? Why don't you use it like env variables?
Just move it to env file and use it here

2024-07-04 08:26 UTC, v12code commented on src/shared/states/ChatStates.ts
> +        const res = await axios.get("https://localhost:7060/api/Chat");
What about try catch?

2024-07-04 08:26 UTC, v12code commented on src/shared/states/ChatStates.ts
> +    error: string,
rename it please to errorMessage

2024-07-04 08:26 UTC, Finka95 commented on src/shared/states/ChatStates.ts
> +    filteredChats: ShortChatType[],
I think you shouldn't store filtered chats here, it should be locally inside component. You don't need to use them somwhere else

2024-07-04 08:26 UTC, Finka95 commented on src/shared/states/ChatStates.ts
> +        set({ success: true, chats: res.data, filteredChats: res.data });
you forgot about loading: false

2024-07-04 08:26 UTC, Finka95 commented on src/modules/ChatListModule/ChatListModule.tsx
> +  const [selectedChat, SetSelectedChat] = useChatState((state) => [
const  {currentChat, setSelectedChat,  filteredChatList, setFilteredChatList, chats, fetchChats} = useChatState(state => ({
currentChat: state.currentChat,
updateCurrentChat: state.updateCurrentChat
........
})

2024-07-04 08:26 UTC, Finka95 commented on src/modules/ChatListModule/ChatListModule.tsx
> +  const [selectedChat, SetSelectedChat] = useChatState((state) => [
Try to keep original names of the variables and methods across the app

2024-07-04 13:00 UTC, v12code commented on src/modules/ChatListModule/ChatListModule.tsx
> +        {filteredChatList.map((item: ShortChatType) => (
you don't need to provide type here. the Item will be typed

2024-07-04 13:01 UTC, Finka95 commented on src/modules/ChatListModule/ChatListModule.tsx
> +  console.log(chats);
try to avoid push this to env's. Especially to prod

2024-07-04 13:02 UTC, Finka95 commented on src/modules/ChatListModule/ChatListModule.tsx
> +  const { currentChat, updateCurrentChat, chats, fetchChats } = useChatState(
currentChat can be named like currentChatId

2024-07-04 13:54 UTC, Finka95 approved these changes

2024-07-04 14:08 UTC, merged