Feature/add user and message slices
Leeyaoi/InnoViber-frontend pull request #29
Opened 2024-07-08 11:49 UTC by Leeyaoi

2024-07-08 12:30 UTC, Finka95 requested changes
Create base useGloabalStore or useAppStore and include all stores in one. and use it inside a component.
Also add cache by "persist" method

2024-07-08 12:30 UTC, Finka95 commented on src/state/UserSlice.ts
> +export const useUserSlice = create<UserSlice>(() => ({
useMessageStore

2024-07-09 07:04 UTC, Finka95 requested changes

2024-07-09 07:04 UTC, Finka95 commented on src/state/UserSlice.ts
> +  ChatSlice & MessageSlice & UserSlice,
Remove unsuitable interfaces

2024-07-09 07:44 UTC, Finka95 approved these changes

2024-07-09 08:25 UTC, MaliyOna approved these changes

2024-07-09 08:26 UTC, merged