Feature/add possibility to change role
Leeyaoi/InnoViber-frontend pull request #43
Opened 2024-07-29 12:52 UTC by Leeyaoi

2024-07-31 06:14 UTC, Finka95 requested changes

2024-07-31 06:14 UTC, Finka95 commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +  const [role, setRole] = useState("");
useState<UserRoles | "">

2024-07-31 06:14 UTC, Finka95 commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +    setRole(event.target.value as string);
setRole(event.target.value as UserRoles);

2024-07-31 06:14 UTC, Finka95 commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +  const getRole = () => {
Remove it

2024-07-31 06:14 UTC, Finka95 commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +    roleObj.role = getRole();
roleObj.role = role as UserRoles;

2024-07-31 06:14 UTC, Finka95 commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +          <MenuItem value="0">Member</MenuItem>
Here you can use static values
MenuItem value={UserRoles.Member}>Member</MenuItem

Or just .map

2024-07-31 06:14 UTC, Finka95 commented on src/components/RoleItem/RoleItem.tsx
> +  const getRoleName = () => {
Please remove it.
Use this UserRoles[UserRoles.Admin] and so on

2024-07-31 06:14 UTC, Finka95 commented on src/components/RoleItem/RoleItem.tsx
> +      {currentRole !== UserRoles.Member &&
optional: here you can use same ruleas as in c# - if conditions become too complex, create method with described name such as "isUserCorrect" and use it

2024-07-31 11:15 UTC, Leeyaoi commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +    setRole(event.target.value as string);
![image](https://github.com/user-attachments/assets/78bf099d-a23e-4713-985a-60b3dd0895d2)

2024-07-31 11:22 UTC, Leeyaoi commented on src/components/ChangeRoleModal/ChangeRoleModal.tsx
> +  const [role, setRole] = useState("");
![image](https://github.com/user-attachments/assets/5b0b0e54-8263-4d6a-84a1-8b785feb75a9)

2024-08-02 11:51 UTC, Finka95 approved these changes

2024-08-02 12:09 UTC, MaliyOna approved these changes

2024-08-02 12:11 UTC, merged